### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by eevans**
There might be a better way, but [0d8ac92](https://github.com/eevans/lastfm_queue/commit/0d8ac928e07b790e48336c7eedb02786bfc5db8e) fixes a bug whereby the queue grows by two tracks for every one played (which also results in  two lastfm API calls per track).

[32ea615](https://github.com/eevans/lastfm_queue/commit/32ea615d05b4207d48f147519f7371116ae61c24) not only results in fewer lastfm API calls, but provides better results for me.

### CODE REVIEW

**Comment by asermax** [comment]
I'll cherry pick 0d8ac92 since it does seems like a bug indeed.

I'm a little reluctant to include 32ea615 since, even when it results in less API calls, it limits the functionality of the plugin in some aspects.
For example, I like adding 4 or 5 initial tracks on my play queue and let the plugin build a nice playlist from there, and deactivate it after I got around 20~ tracks. Imposing a hard limit of 3-5 as you did in your modification, would break that use case. Even more, if I add 5 or more tracks and activate the plugin, suddendly I wouldn't get any similar tracks since it's already over the hard limit, which is kinda inconsistent with the description of the plugin itself.
I'm willing to include it if there was a configuration option to enable/disable this functionality and to set the queue length limit manually, insted of using a hard limit. If you are willing to do it, you'll be very welcome, otherwise I'll try to implement it in a couple of days.

Anyway, thank you very much for contributing :D

**Comment by eevans** [comment]
[ Agustín Carrasco ]

> I'll cherry pick 0d8ac92 since it does seems like a bug indeed.

Great.

> I'm a little reluctant to include 32ea615 since, even when it results in less API calls, it limits the functionality of the plugin in some aspects.
> For example, I like adding 4 or 5 initial tracks on my play queue and let the plugin build a nice playlist from there, and deactivate it after I got around 20~ tracks. Imposing a hard limit of 3-5 as you did in your modification, would break that use case.

While I think your use-case is perfectly valid, allow me to play devil's
advocate for a moment.

I would argue that the expectations of a dynamic queuer like this is to be
fire-and-forget.  A good analogy would be that of a radio station where the
choice of the station gives you some expectation as to the general type of
music, but the playlist itself is outside your control.  I think this is
consistent with an interface consisting of a single button.

Your use case (in my opinion), would be the sort of thing better served by
something similar to the existing playlist creation.  Something where you
create a new playlist, seed it a with a few songs, specify an upper bound
(say 20 tracks), and mash "Create".

> Even more, if I add 5 or more tracks and activate the plugin, suddendly I
> wouldn't get any similar tracks since it's already over the hard limit,
> which is kinda inconsistent with the description of the plugin itself.

You would get new entries, but only after the number of queued tracks got
down to somewhere between 3 and 5.  And this is the reason for the 3-5
range on queue-size, and the 3-5 tracks queued.  If for example you queued
3 when the size reached 3, then the next 3 is always based on the last of
the 3 from the previous run.  Patterns form this way (or at least I
observed as much against my library).

## 

Eric Evans
eevans@sym-link.com

**Comment by asermax** [comment]
Hmm now that you mention it, the use case does fits better as a smart playlist. I'll use that idea on other of the plugins I'm working on ([lastfm_extension](https://github.com/asermax/lastfm_extension). I'll also merge this plugin there. Eventually).

I understand your idea and seems like you thought it through, but I still think the plugin loses some flexibility by imposing this hard limit. I prefer to add a bit of complexity to manage the configs options and allow the user to decide which behavior they prefer acording on how they use the plugin.

**Comment by eevans** [comment]
[ Agustín Carrasco ]

> Hmm now that you mention it, the use case does fits better as a smart playlist. I'll use that idea on other of the plugins I'm working on ([lastfm_extension](https://github.com/asermax/lastfm_extension). I'll also merge this plugin there. Eventually).
> 
> I understand your idea and seems like you thought it through, but I still think the plugin loses some flexibility by imposing this hard limit. I prefer to add a bit of complexity to manage the configs options and allow the user to decide which behavior they prefer acording on how they use the plugin.

Having it configurable is better than not; Agreed

## 

Eric Evans
eevans@sym-link.com

**Pull request closed without merging**
