### PR TITLE
Working in RB 2.99

### PR DESCRIPTION
**Pull request by silberzwiebel**
But I didn't do much testing. Especially I don't know, if it is still working under RB version <= 2.98.

### CODE REVIEW

**Comment by asermax** [comment]
Great! I'm going to do some testing on my machine, where I still have v2.97 and come back at you.
Thanks for the contribution!

**Comment by asermax** [comment]
The toolbar button is gone in 2.97 so I guess this needs some refinement before I can pull it in.
I will try to test and fix this issue during this week report back here :3

**Comment by fossfreedom** [comment]
@asermax - remember - in RB2.99 and later you can no longer modify the toolbar.  It is static.  You can only have source toolbars.

Therefore you may wish to either streamline and keep a consistent lastfmqueue activation method - or have different ways of activating depending upon RB version (toolbar for rb2.96-2.98), menu for RB2.99+

**Comment by asermax** [comment]
Ok, didn't know that, thanks for clarifying it foss :] I probably read it when you first opened the issue about the changes, but guess I forgot.

Anyway, there was a tiny issue with the `Action` state not being correctly set or saved on the settings backend. So I merged this changes and made some changes on top of it to solve that issue.
It would be of great help if you @fossfreedom and @silberzwiebel could test this changes to see if I broke something.

Thanks both for helping me on this one :]

**Comment by silberzwiebel** [comment]
Its not working for me now. The slider of the menu item just randomly turns back to off and no tracks are added to the queue. But there is no error message shown in the console output.
(btw: The settings I didn't set were because of my lack of knowledge of how the whole settings stuff works... )

**Comment by asermax** [comment]
Yeah, I was at loss too. Since the "activated" property is diferent in `GLib.Action` and `Gtk.Action` I didn't find an straightforward way to manage the saved state. 
I will keep looking at it and try to fix it during the week, for now I guess you should use the your branch.
I will get back again if I find something else :3

**Pull request merged**
