### PR TITLE
stateful actioni

### PR DESCRIPTION
**Pull request by fossfreedom**
@asermax - re setting the state of the action.

enc works for RB2.99.  I havent had time to test on rb2.96 - please can you check?

cheers.

### CODE REVIEW

**Comment by asermax** [comment]
It doesn't work correctly on 2.97 since `set_active` fires the `activate` signal, calling the `dinamic_toggle` callback and effectively reversing the actual value.
Maybe adding another method to the `Action` class to get the current state will help avoid using the method of reverting the current `self.active` value, thus removing this bug.

I can fix it myself, but I think it's better if you do it since you're more familiarized with the differences between actions, and you can test it on 2.99 directly (I have set up my test VM with Ubuntu 13.10 but it isn't quite working right now).
Cheers and thanks for the hard work so far :3

**Comment by fossfreedom** [comment]
interesting (sort-of) - looks like a gio.action "set_active" does not fire the activate() signal whereas a gtk.action does fire the activate signal.

ok - I'll look at this tonight.  Probably will fire the activate signal for a gio.action "set_active" so that at least there is consistency.

BTW - brave of you to use 13.10 alpha software!  For me I'm using the "stable" 13.04 + RB2.99 from the gnome 3.8 PPA.

**Comment by asermax** [comment]
I merged your changes and made a slight change to use the `get_active` method you implemented.
It works correctly on v2.97, but it seems to fail on v2.99 since it seems to always return `true` (also, it worries me that it's not capitalized, like the `True` from python). Could you check that out?

**Comment by fossfreedom** [comment]
hmm - yes you are correct

"true" lowercase is the return value of action.get_state() - this is infact a GLib.Variant.  So we can add an if statement to convert from Variant to boolean.

What is puzzling me though is that whilst you can toggle the menu item, the gio.action "state" is never being updated.  Thus - get_state() only ever returns what was initially defined when creating gio.action (i.e. false) or "true" when a set_active is called which in turns does an action.change_state().

Not really sure what to do here - maybe chain the callback ? i.e. when adding the action, the callback added is an internal Action callback.  When the menu is toggled, this Action callback is made which then does a action.change_state() which then calls the original user callback....

There must be an easier way though...

**Pull request merged**
